# Generated by Django 3.1 on 2020-10-16 17:51

from django.db import migrations
from django.utils import timezone

def populate_db(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Comment = apps.get_model('blog', 'Comment')
    p1 = Post(blog_title="Blog 1", 
        blog_content="""Mauris posuere maximus massa eget viverra. Cras pretium est vitae velit aliquam, nec imperdiet magna malesuada. Donec convallis placerat nunc et tempor. Mauris maximus quam non turpis feugiat, quis elementum nunc malesuada. Vestibulum elementum erat est, eget viverra sem tincidunt in. Ut placerat auctor eros, vitae elementum nunc rhoncus vitae. Nulla vitae sodales erat, vel egestas sem. Nam ultricies ut mi sit amet vulputate. Quisque magna tortor, mollis nec posuere quis, imperdiet luctus tortor. Sed et volutpat mauris. Vestibulum cursus porta ornare. Maecenas a rhoncus felis. Etiam hendrerit semper dolor egestas varius.

    Praesent in vehicula purus. Etiam luctus, dui sed rutrum aliquam, ante tellus accumsan ante, in egestas sem orci vitae lectus. Nam aliquam diam ut pellentesque eleifend. Praesent et turpis eu quam euismod malesuada ac a nibh. Quisque fermentum risus a ornare ornare. Proin in hendrerit leo, sed faucibus neque. Curabitur nisl felis, dictum sodales bibendum in, iaculis eget. """,
        blog_author="hank", blog_date=timezone.now())
    p1.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(populate_db)
    ]
